/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author Gabriel
 */
public class Listar extends javax.swing.JFrame {

    /**
     * Creates new form Listar
     */
    
    private String tipo;
    
    public Listar() {
        initComponents();
    }

    public Listar(String tipo, String dados[])
    {
        initComponents();
        this.tipo = tipo;
        carregarLista(dados);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Apagar = new javax.swing.JButton();
        editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabela.setShowGrid(true);
        jScrollPane1.setViewportView(Tabela);

        Apagar.setText("Apagar");

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editar)
                .addGap(238, 238, 238)
                .addComponent(Apagar)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apagar)
                    .addComponent(editar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed


            if(this.tipo == "Medico")
            {
                
            }






    }//GEN-LAST:event_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apagar;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton editar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    private void carregarLista(String[] dados) {
        


    // Nome,CRM, Telefone, Especialidade, Periodo de Atendimento

       if(this.tipo == "Medico")
       {
           DefaultTableModel modelo = (DefaultTableModel) this.Tabela.getModel();
           modelo.setColumnCount(5);
           
           
           
           this.Tabela.setAutoResizeMode( JTable.AUTO_RESIZE_ALL_COLUMNS);
           this.Tabela.setMaximumSize(null);
           
           
           
           
           this.Tabela.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("Nome");
           this.Tabela.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("CRM");
           this.Tabela.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("Telefone");
           this.Tabela.getTableHeader().getColumnModel().getColumn(3).setHeaderValue("Especialidade");
           this.Tabela.getTableHeader().getColumnModel().getColumn(4).setHeaderValue("Período de Atendimento");
       }
       
       //Nome, endereço, telefone, data de nascimento
       
       if(this.tipo == "Paciente")
       {
           DefaultTableModel modelo = (DefaultTableModel) this.Tabela.getModel();
           modelo.setColumnCount(5);
       
           this.Tabela.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("Nome");
           this.Tabela.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("Endereço");
           this.Tabela.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("Telefone");
           this.Tabela.getTableHeader().getColumnModel().getColumn(3).setHeaderValue("Data de Nascimento");
           
       }
       
       
       
       //Nome, CPF, telefone, Rua, Numero, Cep
       
       if(this.tipo == "Funcionário")
       {
           DefaultTableModel modelo = (DefaultTableModel) this.Tabela.getModel();
           modelo.setColumnCount(5);
       
           this.Tabela.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("Nome");
           this.Tabela.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("CRM");
           this.Tabela.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("Telefone");
           this.Tabela.getTableHeader().getColumnModel().getColumn(3).setHeaderValue("Rua");
           this.Tabela.getTableHeader().getColumnModel().getColumn(4).setHeaderValue("Número");
           this.Tabela.getTableHeader().getColumnModel().getColumn(5).setHeaderValue("CEP");
       }
       
      
       
       
       
    }
}
